version: "3"

services:
  postgresLatest:
    image: postgres:1.16
    container_name: postgresLatest
    volumes:
      - /your_postgres_data_path/data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      my_custom_network:
        ipv4_address: 172.23.0.2
  app:
    image: openjdk:17-oracle
    container_name: project-cbs
    working_dir: /app
    expose:
      - 8443
      - 8081
    ports:
      - "8443:8443"
      - "8081:8081"
    volumes:
      - /your_path_to _target/target/project-CBS.jar:/app/app.jar
    entrypoint: ["java", "-jar", "app.jar"]
    networks:
      my_custom_network:
        ipv4_address: 172.23.0.3


networks:
  my_custom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.23.0.0/16