apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: dbServer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbServer
  template:
    metadata:
      labels:
        app: dbServer
    spec:
      containers:
        - name: postgres-container
          image: postgres:17.5
          env:
            - name: POSTGRES_PASSWORD
              value: "mysecretpassword"
          ports:
            - containerPort: 5432